#!/usr/bin bash
echo 'Step 0: Kill ALL THE THINGS... in `public/`'

rm -rf public/*

echo 'Step 1: Copy all the HTML'
mkdir -p public
mkdir -p public/css
cp -v src/index.html public/
mkdir -p public/partials/
 cp -r src/partials/ public/partials/

echo 'Step 2: Build all the Sass into CSS!'
npm run sass

echo 'Step 3: Copy all the JS'
mkdir -p public/js && cp -vr src/js public/

echo 'Step 4: Copy all the `bower_components/`!'

echo 'Step 4a: Normalize the CSS...'
mkdir -p public/bower_components/normalize-css/
cp -v bower_components/normalize-css/normalize.css public/bower_components/normalize-css/normalize.css


mkdir -p public/bower_components/jquery/public/
cp -v bower_components/jquery/public/jquery.js public/bower_components/jquery/public/jquery.js

mkdir -p public/bower_components/angular/
cp -v bower_components/angular/angular.js public/bower_components/angular/angular.js

mkdir -p public/bower_components/angular-route/
cp -v bower_components/angular-route/angular-route.js public/bower_components/angular-route/angular-route.js

mkdir -p public/bower_components/font-awesome/css/
cp -v bower_components/font-awesome/css/font-awesome.css public/bower_components/font-awesome/css/font-awesome.css
